(()=>{
  'use strict';
  const API='/api/crm/prospecting/activity';
  const AUTH='/api/auth/session';
  const DAILY={connections:15,interactions:10,firstMessages:5,followups:5,contentPosts:1,qualifiedReplies:2,meetingsBooked:1};
  const WEEKLY={connections:75,interactions:50,firstMessages:25,followups:25,contentPosts:5,qualifiedReplies:10,meetingsBooked:2};
  const fields=[
    ['connections','Conexões','15/dia'],['interactions','Interações','10/dia'],['firstMessages','1ª mensagens','5/dia'],
    ['followups','Follow-ups','5/dia'],['contentPosts','Conteúdos','1/dia'],['qualifiedReplies','Respostas qualificadas','2/dia'],['meetingsBooked','Reuniões','1/dia']
  ];
  const playbooks={
    agro:{label:'Agronegócio',who:'Cooperativas, revendas, distribuidores, produtores estruturados e empresas com operação de campo.',pain:'Planilhas paralelas, custo por área sem precisão, apontamento tardio e integrações entre ERP, campo, balança e laboratório.',connection:'Olá, [Nome]. Vi a atuação de vocês no agro e trabalho com sistemas sob medida para operações que ainda dependem de planilhas e integrações manuais. Vamos nos conectar?',first:'[Nome], obrigado pela conexão. Hoje o que mais gera retrabalho aí: dado de campo, integração com ERP, custo por operação ou acompanhamento comercial? Pergunto porque esse é exatamente o tipo de processo que estruturamos na Code Solution.',follow:'[Nome], retomando: se você me disser qual processo mais trava a operação hoje, eu consigo te devolver um desenho simples de como eu atacaria isso antes de falar em projeto.'},
    logistica:{label:'Logística e transporte',who:'Transportadoras, operadores logísticos, distribuidores e empresas com frota/entrega.',pain:'Roteirização manual, status por telefone, comprovante em papel, custo por rota e integrações com TMS/ERP.',connection:'Olá, [Nome]. Trabalho com tecnologia para reduzir retrabalho em logística, rastreio e integração operacional. Vi o contexto de vocês e achei válido nos conectarmos.',first:'[Nome], obrigado por aceitar. Hoje vocês têm mais atrito em rastreio/status, comprovante de entrega, roteirização ou integração entre TMS/ERP e operação? A Code Solution costuma entrar exatamente nessas lacunas.',follow:'[Nome], se fizer sentido, posso te mostrar em 15 minutos como normalmente mapeamos o gargalo antes de propor qualquer desenvolvimento.'},
    varejo:{label:'Varejo e distribuição',who:'Distribuidores, atacadistas, redes, e-commerce B2B e operações omnichannel.',pain:'Estoque divergente, pedido redigitado, catálogo/preço por planilha e baixa visibilidade de giro/reposição.',connection:'Olá, [Nome]. Atuo com sistemas e automações para varejo e distribuição, principalmente integração de estoque, força de vendas e processos comerciais. Vamos nos conectar?',first:'[Nome], obrigado pela conexão. Onde vocês perdem mais tempo hoje: integração de estoque/canais, pedido comercial, catálogo/preço ou acompanhamento de giro? Posso compartilhar como temos estruturado esses cenários.',follow:'[Nome], retomando nosso contato: consigo transformar o problema em um diagnóstico curto e te dizer qual seria o primeiro passo sem compromisso de projeto.'},
    processos:{label:'Processos corporativos',who:'PMEs e empresas com equipes operacionais/comerciais usando muitas planilhas, WhatsApp e sistemas desconectados.',pain:'Retrabalho, duplicidade de digitação, aprovações manuais, falta de rastreabilidade e dados espalhados.',connection:'Olá, [Nome]. Trabalho com automação e sistemas sob medida para eliminar processos manuais e conectar operações. Vi o perfil da empresa e gostaria de me conectar.',first:'[Nome], obrigado pela conexão. Existe hoje algum processo que depende demais de planilha, WhatsApp, e-mail ou digitação repetida entre sistemas? Se houver, posso te mostrar como avaliamos isso na Code Solution.',follow:'[Nome], passando para fechar o ciclo: se você me indicar um processo que incomoda hoje, eu te devolvo uma visão objetiva de automação/integração e você decide se vale aprofundar.'}
  };

  let owner='admin';
  let current={};
  const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clamp=(v)=>Math.max(0,Math.min(100000,Math.round(Number(v)||0)));

  function style(){if(document.getElementById('cs-prospecting-ops-style'))return;const s=document.createElement('style');s.id='cs-prospecting-ops-style';s.textContent=`
  #csProspectingOps{margin-bottom:14px}.csops-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:14px}.csops-panel{background:linear-gradient(145deg,#111827,#0d121e);border:1px solid rgba(255,255,255,.09);border-radius:15px;padding:16px}.csops-title{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.csops-title h2{font-size:16px;margin:0}.csops-owner{margin-left:auto;color:#48d99b;font-size:12px}.csops-fields{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin:13px 0}.csops-field{background:#0a101b;border:1px solid rgba(255,255,255,.08);border-radius:11px;padding:10px}.csops-field label{display:block;color:#8f9bae;font-size:11px}.csops-field input{width:100%;margin-top:6px;background:#08111c;border:1px solid #2c4154;border-radius:8px;color:#fff;padding:8px;font:700 18px system-ui}.csops-field small{color:#6f8094}.csops-actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.csops-status{font-size:12px;color:#8f9bae}.csops-bars{display:grid;gap:8px;margin-top:12px}.csops-bar{display:grid;grid-template-columns:130px 1fr 76px;gap:8px;align-items:center;font-size:11px}.csops-track{height:8px;background:#09111b;border-radius:999px;overflow:hidden}.csops-fill{height:100%;background:linear-gradient(90deg,#42a7ff,#48d99b);border-radius:999px}.csops-icp{display:grid;gap:10px}.csops-icp select{width:100%;background:#0a101b;border:1px solid #2c4154;border-radius:9px;color:#fff;padding:9px}.csops-copy{border:1px solid rgba(255,255,255,.08);border-radius:10px;padding:10px;background:#0a101b}.csops-copy b{font-size:11px;color:#8f9bae;text-transform:uppercase}.csops-copy p{margin:5px 0 8px;color:#d5dde7;font-size:12px}.csops-copy button{border:1px solid #31506b;background:#101c2a;color:#bfe1ff;border-radius:8px;padding:6px 8px;cursor:pointer}.csops-meta{font-size:11px;color:#8f9bae;margin-top:9px}.csops-week{margin-top:12px;overflow:auto}.csops-week table{width:100%;border-collapse:collapse;min-width:650px}.csops-week th,.csops-week td{padding:7px;border-bottom:1px solid rgba(255,255,255,.06);font-size:11px;text-align:left}.csops-week th{color:#8f9bae}@media(max-width:1050px){.csops-grid{grid-template-columns:1fr}.csops-fields{grid-template-columns:repeat(3,1fr)}}@media(max-width:650px){.csops-fields{grid-template-columns:repeat(2,1fr)}.csops-bar{grid-template-columns:100px 1fr 66px}}
  `;document.head.appendChild(s);}

  function mount(){const wrap=document.querySelector('main.wrap')||document.querySelector('main');const head=wrap?.querySelector('.head');if(!wrap||document.getElementById('csProspectingOps'))return;style();const el=document.createElement('section');el.id='csProspectingOps';el.innerHTML=`<div class="csops-grid"><div class="csops-panel"><div class="csops-title"><h2>Execução de hoje · LinkedIn</h2><span class="csops-owner" id="csopsOwner">carregando usuário…</span></div><div class="sub">Registre o realizado. Meta diária: 15 conexões, 10 interações, 5 primeiras mensagens, 5 follow-ups e 1 conteúdo.</div><div class="csops-fields">${fields.map(([k,l,t])=>`<div class="csops-field"><label for="csops-${k}">${l}</label><input id="csops-${k}" data-k="${k}" type="number" min="0" step="1" value="0"><small>${t}</small></div>`).join('')}</div><div class="csops-actions"><button class="btn primary" id="csopsSave">Salvar execução</button><button class="btn" id="csopsReload">Recarregar</button><span class="csops-status" id="csopsStatus"></span></div><div class="csops-bars" id="csopsBars"></div><div class="csops-week" id="csopsWeek"></div></div><div class="csops-panel"><div class="csops-title"><h2>Playbook por ICP</h2></div><div class="sub">Escolha o segmento do bloco de prospecção e personalize antes de enviar.</div><div class="csops-icp"><select id="csopsIcp">${Object.entries(playbooks).map(([k,v])=>`<option value="${k}">${v.label}</option>`).join('')}</select><div id="csopsIcpBody"></div></div></div></div>`;head?.insertAdjacentElement('afterend',el)||wrap.prepend(el);bind();renderIcp();load();}

  async function session(){try{const r=await fetch(AUTH,{credentials:'same-origin'});const x=await r.json();if(r.ok&&x.ok&&x.user?.username)owner=String(x.user.username).toLowerCase();}catch{}document.getElementById('csopsOwner').textContent=`Responsável: ${owner}`;}
  async function load(){await session();status('Atualizando…');try{const r=await fetch(`${API}?days=7&channel=linkedin&owner=${encodeURIComponent(owner)}`,{credentials:'same-origin'});const x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||`HTTP ${r.status}`);current=x;const row=(x.rows||[]).find(v=>v.date===x.today&&String(v.owner).toLowerCase()===owner)||{};for(const [k] of fields){const input=document.getElementById(`csops-${k}`);if(input)input.value=Number(row[k]||0);}renderBars(x.totals||{});renderWeek(x.rows||[]);status(`Última atualização: ${new Date(x.generatedAt).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`);}catch(e){status(`Erro ao carregar: ${e.message}`,true);}}
  async function save(){const body={date:today(),owner,channel:'linkedin'};for(const [k] of fields)body[k]=clamp(document.getElementById(`csops-${k}`)?.value);status('Salvando…');try{const r=await fetch(API,{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||`HTTP ${r.status}`);status('Execução salva no CRM.');await load();}catch(e){status(`Erro ao salvar: ${e.message}`,true);}}
  function renderBars(t){const box=document.getElementById('csopsBars');box.innerHTML='<b style="font-size:12px">Progresso dos últimos 7 dias</b>'+fields.map(([k,l])=>{const goal=WEEKLY[k]||0,val=Number(t[k]||0),p=goal?Math.min(100,Math.round(val/goal*100)):0;return `<div class="csops-bar"><span>${l}</span><div class="csops-track"><div class="csops-fill" style="width:${p}%"></div></div><strong>${val}/${goal}</strong></div>`}).join('');}
  function renderWeek(rows){const box=document.getElementById('csopsWeek');const list=[...rows].sort((a,b)=>String(b.date).localeCompare(String(a.date)));box.innerHTML=`<table><thead><tr><th>Data</th><th>Conexões</th><th>Interações</th><th>1ª msgs</th><th>Follow-ups</th><th>Conteúdo</th><th>Resp. qualif.</th><th>Reuniões</th></tr></thead><tbody>${list.length?list.map(r=>`<tr><td>${esc(r.date)}</td><td>${r.connections}</td><td>${r.interactions}</td><td>${r.firstMessages}</td><td>${r.followups}</td><td>${r.contentPosts}</td><td>${r.qualifiedReplies}</td><td>${r.meetingsBooked}</td></tr>`).join(''):'<tr><td colspan="8">Nenhuma execução registrada ainda.</td></tr>'}</tbody></table>`;}
  function renderIcp(){const key=document.getElementById('csopsIcp')?.value||'agro',p=playbooks[key],body=document.getElementById('csopsIcpBody');if(!body)return;body.innerHTML=`<div class="csops-meta"><b>Quem priorizar:</b> ${esc(p.who)}</div><div class="csops-meta"><b>Dor para investigar:</b> ${esc(p.pain)}</div>${[['Conexão',p.connection],['Após aceitar',p.first],['Follow-up',p.follow]].map(([t,txt])=>`<div class="csops-copy"><b>${t}</b><p>${esc(txt)}</p><button data-copy="${esc(txt)}">Copiar</button></div>`).join('')}<div class="csops-meta">UTM sugerida: <code>utm_source=linkedin&utm_medium=organic&utm_campaign=${key}_prospeccao</code></div>`;body.querySelectorAll('[data-copy]').forEach(b=>b.addEventListener('click',()=>copy(b.getAttribute('data-copy'),b)));}
  async function copy(text,btn){try{await navigator.clipboard.writeText(text);const old=btn.textContent;btn.textContent='Copiado';setTimeout(()=>btn.textContent=old,1200);}catch{}}
  function status(text,error=false){const el=document.getElementById('csopsStatus');if(el){el.textContent=text;el.style.color=error?'#ff9fac':'#8f9bae';}}
  function bind(){document.getElementById('csopsSave')?.addEventListener('click',save);document.getElementById('csopsReload')?.addEventListener('click',load);document.getElementById('csopsIcp')?.addEventListener('change',renderIcp);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
