(()=>{
  'use strict';
  const API='/api/crm/prospecting/activity';
  const AUTH='/api/auth/session';
  const DAILY={connections:15,interactions:10,firstMessages:5,followups:5,contentPosts:1,qualifiedReplies:2,meetingsBooked:1};
  const WEEKLY={connections:75,interactions:50,firstMessages:25,followups:25,contentPosts:5,qualifiedReplies:10,meetingsBooked:2};
  const LABELS={connections:'Conexões',interactions:'Interações',firstMessages:'1ª mensagens',followups:'Follow-ups',contentPosts:'Conteúdos',qualifiedReplies:'Respostas qualif.',meetingsBooked:'Reuniões'};
  let owner='admin';
  const pct=(value,goal)=>goal?Math.round((Number(value||0)/goal)*100):0;
  const cap=(value)=>Math.max(0,Math.min(100,value));
  const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

  function addStyle(){if(document.getElementById('cs-goal-style'))return;const s=document.createElement('style');s.id='cs-goal-style';s.textContent=`
  .csgoal{margin:0 0 14px;background:linear-gradient(145deg,#111827,#0d121e);border:1px solid rgba(255,255,255,.09);border-radius:15px;padding:16px}.csgoal-head{display:flex;align-items:flex-end;gap:12px;flex-wrap:wrap;margin-bottom:12px}.csgoal-head h2{font-size:16px;margin:0}.csgoal-head p{margin:0;color:#8f9bae;font-size:12px}.csgoal-stamp{margin-left:auto;color:#48d99b;font-size:11px}.csgoal-overall{display:grid;grid-template-columns:repeat(2,minmax(220px,1fr));gap:10px;margin-bottom:12px}.csgoal-overall-card{padding:13px;border:1px solid rgba(255,255,255,.08);border-radius:12px;background:#0a101b}.csgoal-overall-card small{display:block;color:#8f9bae}.csgoal-overall-card strong{display:block;font-size:23px;margin:2px 0}.csgoal-metrics{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr));gap:9px}.csgoal-card{padding:11px;border:1px solid rgba(255,255,255,.08);border-radius:11px;background:#0a101b}.csgoal-card-top{display:flex;justify-content:space-between;gap:8px;align-items:center}.csgoal-card b{font-size:11px;color:#c9d4df}.csgoal-card strong{font-size:13px}.csgoal-track{height:7px;background:#08111c;border-radius:999px;overflow:hidden;margin:8px 0 5px}.csgoal-fill{height:100%;border-radius:999px;background:linear-gradient(90deg,#42a7ff,#48d99b)}.csgoal-card small{color:#8f9bae;font-size:10px}.csgoal-card[data-state="below"] .csgoal-fill{background:linear-gradient(90deg,#ff8a65,#ffc45f)}.csgoal-card[data-state="done"] strong{color:#48d99b}@media(max-width:1000px){.csgoal-metrics{grid-template-columns:repeat(3,1fr)}}@media(max-width:650px){.csgoal-overall{grid-template-columns:1fr}.csgoal-metrics{grid-template-columns:repeat(2,1fr)}}`;
  document.head.appendChild(s);}

  async function resolveOwner(){try{const r=await fetch(AUTH,{credentials:'same-origin'});const x=await r.json();if(r.ok&&x.ok&&x.user?.username)owner=String(x.user.username).toLowerCase();}catch{}}
  function averageProgress(values,targets){const keys=Object.keys(targets);return Math.round(keys.reduce((sum,k)=>sum+cap(pct(values?.[k],targets[k])),0)/keys.length);}
  function metricCards(values,targets,prefix){return Object.keys(targets).map(k=>{const value=Number(values?.[k]||0),goal=targets[k],percent=pct(value,goal),state=value>=goal?'done':'below';return `<div class="csgoal-card" data-state="${state}"><div class="csgoal-card-top"><b>${esc(LABELS[k]||k)}</b><strong>${value}/${goal}</strong></div><div class="csgoal-track"><div class="csgoal-fill" style="width:${cap(percent)}%"></div></div><small>${prefix}: ${Math.max(0,percent)}% da meta</small></div>`;}).join('');}
  function ensureBox(){let box=document.getElementById('csGoalEvidence');if(box)return box;const ops=document.getElementById('csProspectingOps');if(!ops)return null;addStyle();box=document.createElement('section');box.id='csGoalEvidence';box.className='csgoal';box.innerHTML='<div class="csgoal-head"><div><h2>Realizado × Meta</h2><p>Evidência operacional do LinkedIn — hoje e últimos 7 dias.</p></div><span class="csgoal-stamp" id="csGoalStamp">carregando…</span></div><div id="csGoalBody"></div>';ops.insertAdjacentElement('afterend',box);return box;}
  async function render(){await resolveOwner();const box=ensureBox();if(!box)return;const stamp=document.getElementById('csGoalStamp'),body=document.getElementById('csGoalBody');try{const r=await fetch(`${API}?days=7&channel=linkedin&owner=${encodeURIComponent(owner)}`,{credentials:'same-origin',cache:'no-store'});const x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||`HTTP ${r.status}`);const today=x.todayTotals||{},week=x.totals||{};const dailyScore=averageProgress(today,DAILY),weeklyScore=averageProgress(week,WEEKLY);body.innerHTML=`<div class="csgoal-overall"><div class="csgoal-overall-card"><small>Execução de hoje</small><strong>${dailyScore}%</strong><div class="csgoal-track"><div class="csgoal-fill" style="width:${cap(dailyScore)}%"></div></div><small>média do realizado sobre as metas diárias</small></div><div class="csgoal-overall-card"><small>Execução da semana</small><strong>${weeklyScore}%</strong><div class="csgoal-track"><div class="csgoal-fill" style="width:${cap(weeklyScore)}%"></div></div><small>últimos 7 dias × metas semanais</small></div></div><div class="csgoal-metrics">${metricCards(today,DAILY,'Hoje')}</div><div style="height:10px"></div><div class="csgoal-metrics">${metricCards(week,WEEKLY,'7 dias')}</div>`;stamp.textContent=`Responsável: ${owner} · atualizado ${new Date(x.generatedAt).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`;}catch(e){body.innerHTML=`<div style="color:#ff9fac">Não foi possível carregar realizado × meta: ${esc(e.message)}</div>`;stamp.textContent='erro de leitura';}}
  function boot(){const tryMount=()=>{if(document.getElementById('csProspectingOps')){render();const save=document.getElementById('csopsSave');if(save&&!save.dataset.goalHook){save.dataset.goalHook='1';save.addEventListener('click',()=>setTimeout(render,1200));}const reload=document.getElementById('csopsReload');if(reload&&!reload.dataset.goalHook){reload.dataset.goalHook='1';reload.addEventListener('click',()=>setTimeout(render,500));}}else setTimeout(tryMount,250);};tryMount();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
