(() => {
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const firstName=v=>String(v||'').trim().split(/\s+/)[0]||'tudo bem';
  function detectSolution(lead){const text=`${lead?.need||''} ${lead?.segment||''}`.toLowerCase();if(/integra|api|erp|crm|sistema[s]? desconect/.test(text))return'Integrações';if(/automat|manual|retrabalho|planilha|repetitiv/.test(text))return'Automação';if(/ia|intelig|agente|chat|assistente/.test(text))return'IA / Agentes';if(/dashboard|painel|indicador|bi|dados|relat/.test(text))return'Dados & BI';return'Software sob medida';}
  function discovery(lead){const solution=detectSolution(lead);const common=['Qual processo hoje está causando mais retrabalho?','Quem executa esse processo e quem toma a decisão final?','Qual impacto do problema em tempo, custo, venda ou operação?','Existe prazo ou evento que torne essa demanda urgente?','Já existe orçamento ou faixa de investimento prevista?'];const extra={
    'Integrações':['Quais sistemas precisam trocar dados?','Hoje existe API, exportação de arquivo ou trabalho manual entre eles?'],
    'Automação':['Quais passos são repetidos e com que frequência?','Onde acontecem erros, atrasos ou dupla digitação?'],
    'IA / Agentes':['Que conhecimento a IA precisa consultar?','Qual decisão deve permanecer obrigatoriamente com uma pessoa?'],
    'Dados & BI':['Quais decisões precisam ser tomadas com esses dados?','Quais fontes hoje precisam ser consolidadas?'],
    'Software sob medida':['Quem serão os usuários principais?','Qual é o fluxo mínimo que já geraria valor numa primeira versão?']
  }[solution]||[];return {solution,questions:[...common,...extra]};}
  function templates(lead){const name=firstName(lead?.name);const company=lead?.company?` da ${lead.company}`:'';const need=String(lead?.need||'').trim();const context=need?` Vi que a necessidade está relacionada a ${need.slice(0,140)}${need.length>140?'…':''}.`:'';return{
    first:`Olá, ${name}! Aqui é da Code Solution.${context} Quero entender rapidamente o cenário para direcionarmos a melhor solução, sem te fazer perder tempo. Posso te fazer algumas perguntas objetivas?`,
    discovery:`${name}, pelo que entendi até aqui, o próximo passo ideal é fazermos uma conversa de discovery para mapear processo, impacto, integrações e prioridade. Assim conseguimos te devolver um direcionamento técnico e comercial mais preciso. Qual melhor horário para você?`,
    follow:`Olá, ${name}! Retomando nosso contato sobre a demanda${company}. Queria confirmar se o projeto continua como prioridade e se existe alguma informação ou decisão que esteja impedindo o próximo passo. Posso te ajudar a destravar isso?`,
    proposal:`${name}, consolidamos o entendimento da demanda e estamos avançando para a proposta. Antes de finalizar, quero confirmar três pontos para evitar desalinhamento: escopo prioritário, prazo desejado e quem participa da decisão. Podemos validar isso juntos?`
  };}
  async function copy(text,button){try{await navigator.clipboard.writeText(text);const old=button.textContent;button.textContent='Copiado ✓';setTimeout(()=>button.textContent=old,1400);}catch{prompt('Copie a mensagem:',text)}}
  function ensure(){if(document.getElementById('cs-playbook'))return;const quick=document.querySelector('.quick');if(!quick)return;const box=document.createElement('section');box.id='cs-playbook';box.className='cs-playbook';box.innerHTML=`<div class="cs-pb-head"><div><span>Playbook comercial</span><h2>Próxima melhor abordagem</h2></div><b id="csPbSolution">—</b></div><div id="csPbSla" class="cs-pb-sla"></div><div class="cs-pb-grid"><div class="cs-pb-panel"><h3>Mensagem sugerida</h3><textarea id="csPbMessage" readonly></textarea><div class="cs-pb-buttons"><button class="btn" data-template="first">Primeiro contato</button><button class="btn" data-template="discovery">Discovery</button><button class="btn" data-template="follow">Follow-up</button><button class="btn" data-template="proposal">Proposta</button><button id="csPbCopy" class="btn green">Copiar mensagem</button></div></div><div class="cs-pb-panel"><h3>Perguntas recomendadas</h3><ol id="csPbQuestions"></ol></div></div><div class="cs-pb-rules"><b>Regras de atendimento:</b> não prometer prazo/preço antes do entendimento técnico · sempre identificar decisor · toda conversa termina com próxima ação e data · registrar objeções no CRM.</div>`;quick.insertAdjacentElement('beforebegin',box);box.addEventListener('click',e=>{const t=e.target.closest('[data-template]');if(t && typeof active!=='undefined' && active){const map=templates(active);document.getElementById('csPbMessage').value=map[t.dataset.template]||map.first;}if(e.target.id==='csPbCopy')copy(document.getElementById('csPbMessage').value,e.target);});}
  function render(){ensure();if(typeof active==='undefined'||!active||!document.getElementById('cs-playbook'))return;const d=discovery(active),tpl=templates(active);document.getElementById('csPbSolution').textContent=d.solution;document.getElementById('csPbMessage').value=tpl.first;document.getElementById('csPbQuestions').innerHTML=d.questions.map(q=>`<li>${esc(q)}</li>`).join('');const created=new Date(active.createdAt||active.created_at||0).getTime();const hours=created?(Date.now()-created)/3600000:0;const isNew=String(active.status||'')==='novo';const overdue=isNew&&hours>4;document.getElementById('csPbSla').innerHTML=overdue?`<strong>SLA vencido:</strong> este lead está novo há ${Math.floor(hours)}h. Priorize o contato agora.`:isNew?`<strong>SLA ativo:</strong> primeiro contato recomendado em até 4 horas.`:`<strong>Etapa atual:</strong> ${esc(active.status||'em atendimento')} · mantenha próxima ação e data registradas.`;document.getElementById('csPbSla').classList.toggle('late',overdue);}
  const style=document.createElement('style');style.textContent=`.cs-playbook{margin:0 0 16px;padding:14px;border:1px solid var(--line);border-radius:14px;background:#0a101b}.cs-pb-head{display:flex;justify-content:space-between;gap:10px;align-items:center;margin-bottom:10px}.cs-pb-head span{display:block;color:var(--purple);font-size:10px;text-transform:uppercase;letter-spacing:.14em;font-weight:900}.cs-pb-head h2{margin:2px 0 0;font-size:17px}.cs-pb-head>b{background:#171e2c;padding:6px 9px;border-radius:999px;font-size:11px}.cs-pb-sla{padding:9px 10px;border-radius:10px;background:rgba(72,217,155,.07);border:1px solid rgba(72,217,155,.18);margin-bottom:10px;font-size:12px}.cs-pb-sla.late{background:rgba(255,111,132,.08);border-color:rgba(255,111,132,.26);color:#ffc1ca}.cs-pb-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:10px}.cs-pb-panel{border:1px solid var(--line);border-radius:11px;padding:11px;background:#0d1420}.cs-pb-panel h3{margin:0 0 8px;font-size:13px}.cs-pb-panel textarea{width:100%;min-height:118px;background:#08101a;color:var(--text);border:1px solid var(--line);border-radius:9px;padding:10px;resize:vertical}.cs-pb-panel ol{margin:0;padding-left:20px;color:#c8d2de;font-size:12px}.cs-pb-panel li{margin:0 0 6px}.cs-pb-buttons{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.cs-pb-buttons .btn{font-size:11px;padding:7px 8px}.cs-pb-rules{margin-top:9px;color:var(--muted);font-size:11px}@media(max-width:820px){.cs-pb-grid{grid-template-columns:1fr}}`;document.head.appendChild(style);
  let last='';setInterval(()=>{if(typeof active==='undefined'||!active)return;const sig=`${active.id}:${active.status}:${active.updatedAt||active.updated_at||''}`;if(sig!==last){last=sig;render();}},800);window.addEventListener('load',()=>setTimeout(render,500));
})();
